apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=db;Database=MyDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;"
