{
 "title": "Default Dashbord",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Avergage latency (API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m]))\r\n/\r\nsum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Traffic (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  http_request_duration_seconds_count{\r\n    controller=\"WorldCity\",\r\n    action=\"GetById\"\r\n  }\r\n)",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(\r\n  http_request_duration_seconds_count{\r\n    code=\"200\",\r\n    controller=\"WorldCity\",\r\n    action=\"GetById\"\r\n  }\r\n)",
     "legendFormat": "Successful Requests"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{code=~\"4..|5..\"})",
     "legendFormat": "Failed requests"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"POST\"})",
     "legendFormat": "Post"
    }
   ]
  },
  {
   "title": "Request Throughput by Endpoint",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (action) (\r\n  increase(http_request_duration_seconds_count[5m])\r\n)",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}