apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.password: "$2y$05$qAdCaW.Xg3E8XglR5qTKyO/ebX5mR5tnJ.olGVVBQrvQRsfQa1EIC"
  admin.passwordMtime: "2026-06-19T12:00:00Z"
