argo-cd:
  server:
    extraArgs:
      - --rootpath=/argocd
      - --basehref=/argocd
  configs:
    params:
      server.insecure: true
    secret:
      createSecret: false
      existingSecret: argocd-admin-secret
