name: Validate API

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Verify tools
        run: |
          docker --version
          kubectl version --client

      - name: Debug repo structure
        run: |
          find . -type f | grep dockerfile
          find . -type d | sort

      - name: build docker image
        run: docker build -t api:dev -f /home/runner/work/DevOps-project/DevOps-project/apps/api/api/Dockerfile apps/api

      - name: Create Kind cluster
        uses: helm/kind-action@v1

      - name: Make image available for kind
        run: kind load docker-image api:dev

      - name: Deploy database
        run: |
          kubectl apply -f k8s/secrets/
          kubectl apply -f k8s/deployments/database.yml
          kubectl apply -f k8s/services/database-svc.yml

      - name: Deploy api
        run: |
          kubectl apply -f k8s/deployments/api.yml
          kubectl apply -f k8s/services/api-svc.yml

      - name: List pods
        run: kubectl get pods -A
