name: Validate API

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Verify tools
        run: |
          docker --version
          kubectl version --client

      - name: build docker image
        run: docker build -t api:dev -f apps/api/api/dockerfile apps/api

      - name: Create Kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: dev

      - name: Make image available for kind
        run: kind load docker-image api:dev --name dev

      - name: Deploy database
        run: |
          kubectl apply -f k8s/secrets/
          kubectl apply -f k8s/deployments/database.yml
          kubectl apply -f k8s/services/database-svc.yml

      - name: Deploy api
        run: |
          kubectl apply -f k8s/deployments/api.yml
          kubectl apply -f k8s/services/api-svc.yml

      - name: List pods
        run: kubectl get pods -A

      - name: Wait for api
        run: kubectl wait --for=condition=available deployment/api --timeout=120s

      - name: Forward port API
        run: kubectl port-forward svc/api 8080:80
        #localhost 8080

      - name: Create world city
        run: |
          curl -X POST http://localhost:8080/api/worldcity \
          -H "Content-Type: application/json" \
          -d '{"city":"Malmö", "country":"Sweden", "population":350000}'

      - name: Get world city
        run: |
          response=$(curl -s http://localhost:8080/api/worldcity/Malmö)
          echo "$response
