name: Validate API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Verify tools
        run: |
          docker --version
          kubectl version --client

      - name: Build API image
        run: docker build -t api:dev -f apps/api/api/dockerfile apps/api

      - name: Create Kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: dev

      - name: Make image available for kind
        run: kind load docker-image api:dev --name dev

      - name: Deploy database
        run: |
          kubectl apply -f k8s/apps/secrets/
          kubectl apply -f k8s/apps/deployments/database.yml
          kubectl apply -f k8s/apps/services/database-svc.yml

      - name: Wait for pod db
        run: |
          kubectl wait \
            --for=condition=Ready \
            pod \
            -l app=db \
            --timeout=120s

      - name: Deploy api
        run: |
          kubectl apply -f k8s/apps/deployments/api.yml
          kubectl apply -f k8s/apps/services/api-svc.yml

      - name: Wait for pod API
        run: |
          kubectl wait \
            --for=condition=Ready \
            pod \
            -l app=api \
            --timeout=120s

      - name: List pods & services
        run: |
          kubectl get pods -A
          kubectl get svc -A

      - name: Port forward
        run: |
          kubectl port-forward svc/api 8080:80 &
          sleep 5
        # & allows us to continue the script - otherwise it gets stuck

      - name: Create world city
        run: |
          curl -X POST http://localhost:8080/api/worldcity \
          -H "Content-Type: application/json" \
          -d '{"city":"Malmö", "country":"Sweden", "population":350000}'

      - name: Get world city
        run: |
          response=$(curl -s http://localhost:8080/api/worldcity/1)
          echo "$response"
